apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.api.name}}-secret
type: Opaque
data:
  database-url: {{ printf "postgresql://%s:%s@%s-clusterip:%d/%s" 
  .Values.database.user 
  .Values.database.password 
  .Values.database.host 
  (.Values.postgres.port | int64)
  .Values.database.db| b64enc | quote}}