# {{- define "chart.labels"}}
#   labels:
#     date: {{now | htmlDate}}
#     version: {{.Values.app.version}}
# {{- end}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  #{{- template "chart.labels" .}}
  #{{- include "chart.labels" . | indent 2}}
data:
  key: {{ .Release.Name }}
  name: {{ quote .Values.name }}
  surname: {{ upper .Values.surname | quote }}
  chart: {{ quote .Chart.Version }}
  date: {{ now | date "2006-01-02" | quote }}
  {{- if eq .Values.env "production"}}
  paymentToken: "1234"
  {{- else }}
  paymentToken: false
  {{- end}}
  {{- with .Values.value.requirements.limits}}
  memory: {{.memory}}
  cpu: {{.cpu}}
  version: {{$.Release.Name}}
  {{- end}}
  {{- $map := $.Release.Name | upper | quote }}
  map: {{$map}}
  # {{- range tuple "Anton" "Vasia"}}
  # - {{.}}
  # {{- end}}
  users: |-
    {{- range $index, $user :=.Values.users}}
    - {{$user.name}}: "{{$user.role}} - {{$index}}"
    {{- end}}
