apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.postgres.name}}-secret
type: Opaque
data:
  postgres-db: {{.Values.database.db | b64enc}}
  postgres-user: {{.Values.database.user | b64enc}}
  postgres-password: {{.Values.database.password | b64enc}}